PUT http://localhost:2560 /circuit/34o7j1pf6ta0
Content-Type: application/json

{
    "circuitName": "Test",
    "components": [
        "std/and",
        "std/buffer",
        "std/clock",
        "std/input",
        "std/nand",
        "std/nor",
        "std/not",
        "std/or",
        "std/output",
        "std/splitter",
        "std/xnor",
        "std/xor"
    ],
    "content": {
        "0": {
            "identifier": "std/input",
            "label": "",
            "direction": 0,
            "flip": false,
            "position": [
                0,
                0
            ],
            "outputs": {
                "i": [
                    [
                        1,
                        "o"
                    ]
                ]
            },
            "wires": {
                "1": [
                    {
                        "coords": [],
                        "inputIndex": 0,
                        "outputIndex": 0
                    }
                ]
            }
        },
        "1": {
            "identifier": "std/output",
            "label": "",
            "direction": 0,
            "flip": false,
            "position": [
                2,
                0
            ],
            "outputs": {},
            "wires": {}
        }
    },
    "ownerEmail": "a@b.c"
}

###
