GET http://localhost:2560/circuit/3t1iwo7jtck0
Accept: application/json
Cookie: userId=aunpw
userId: aunpw

### Owner

GET http://localhost:2560/circuit/3t1iwo7jtck0
Accept: application/json
Cookie: userId=bunpw
userId: bunpw